// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/outfits/generate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/outfits/generate.post').default>>>>
    }
    '/api/outfits': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/outfits/index.get').default>>>>
    }
    '/api/wardrobe/analyze': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/wardrobe/analyze.post').default>>>>
    }
    '/api/wardrobe/items': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/wardrobe/items.get').default>>>>
    }
    '/api/wardrobe/upload': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/wardrobe/upload.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}